country_languages = {
    'Netherlands': ['Dutch', 'nl'],
    'South Korea': ['Korean', 'ko'],
    'Nigeria': ['English', 'en'],
    'Spain': ['Spanish', 'es'],
    'Morocco': ['Arabic', 'ar'],
    'India': ['Hindi', 'hi'],
    'United Kingdom': ['English', 'en'],
    'Vietnam': ['Vietnamese', 'vi'],
    'Malaysia': ['Malay', 'ms'],
    'Chile': ['Spanish', 'es'],
    'Zimbabwe': ['English', 'en'],
    'Egypt': ['Arabic', 'ar'],
    'Japan': ['Japanese', 'ja'],
    'Iran': ['Persian', 'fa'],
    'Philippines': ['Filipino', 'fil'],
    'Israel': ['Hebrew', 'he'],
    'Bangladesh': ['Bengali', 'bn'],
    'Lebanon': ['Arabic', 'ar'],
    'Ukraine': ['Ukrainian', 'uk'],
    'United States': ['English', 'en'],
    'Czech Republic': ['Czech', 'cs'],
    'Italy': ['Italian', 'it'],
    'Indonesia': ['Indonesian', 'id'],
    'France': ['French', 'fr'],
    'Mexico': ['Spanish', 'es'],
    'Saudi Arabia': ['Arabic', 'ar'],
    'Nepal': ['Nepali', 'ne'],
    'Romania': ['Romanian', 'ro'],
    'Germany': ['German', 'de'],
    'Pakistan': ['Urdu', 'ur'],
    'Brazil': ['Portuguese', 'pt'],
    'Russia': ['Russian', 'ru'],
    'Taiwan': ['Mandarin Chinese', 'zh'],
    'Hong Kong': ['Cantonese', 'zh-yue'],
    'Peru': ['Spanish', 'es'],
    'Singapore': ['English', 'en'],
    'Turkey': ['Turkish', 'tr'],
    'New Zealand': ['English', 'en'],
    'Poland': ['Polish', 'pl'],
    'Argentina': ['Spanish', 'es'],
    'China': ['Mandarin Chinese', 'zh'],
    'South Africa': ['English', 'en'],
    'Thailand': ['Thai', 'th'],
    'Australia': ['English', 'en'],
    'Canada': ['English', 'en']
}